"""initial schema

Revision ID: 60225360476a
Revises: 
Create Date: 2026-09-16 01:04:56.881690
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import app.db.base

revision = '60225360476a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # pgvector must exist before any Vector column is created. On SQLite the
    # Vector type degrades to TEXT, so this is a no-op there.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('function', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_cache_request_hash'), ['request_hash'], unique=True)

    op.create_table('skills',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('aliases', app.db.base.JSONColumn(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('agents',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=False),
    sa.Column('config', app.db.base.JSONColumn(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_agent_key')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_user_id'), ['user_id'], unique=False)

    op.create_table('ai_usage',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('function', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_function'), ['function'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_request_hash'), ['request_hash'], unique=False)
        batch_op.create_index('ix_ai_usage_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('before', app.db.base.JSONColumn(), nullable=True),
    sa.Column('after', app.db.base.JSONColumn(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_logs_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('career_profiles',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('links', app.db.base.JSONColumn(), nullable=False),
    sa.Column('total_experience_years', sa.Float(), nullable=False),
    sa.Column('domains', app.db.base.JSONColumn(), nullable=False),
    sa.Column('preferred_roles', app.db.base.JSONColumn(), nullable=False),
    sa.Column('preferred_industries', app.db.base.JSONColumn(), nullable=False),
    sa.Column('notice_period', sa.String(length=100), nullable=False),
    sa.Column('current_ctc_lpa', sa.Float(), nullable=True),
    sa.Column('expected_ctc_lpa', sa.Float(), nullable=True),
    sa.Column('work_authorization', sa.Boolean(), nullable=False),
    sa.Column('work_authorization_note', sa.String(length=300), nullable=False),
    sa.Column('open_to_relocation', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('career_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('encrypted_secrets',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('hint', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_error', sa.Text(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_secret_key')
    )
    with op.batch_alter_table('encrypted_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encrypted_secrets_user_id'), ['user_id'], unique=False)

    op.create_table('job_preferences',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('target_roles', app.db.base.JSONColumn(), nullable=False),
    sa.Column('preferred_locations', app.db.base.JSONColumn(), nullable=False),
    sa.Column('remote_ok', sa.Boolean(), nullable=False),
    sa.Column('remote_only', sa.Boolean(), nullable=False),
    sa.Column('min_salary_lpa', sa.Float(), nullable=True),
    sa.Column('target_salary_lpa', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('experience_min_years', sa.Float(), nullable=True),
    sa.Column('experience_max_years', sa.Float(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=False),
    sa.Column('employment_types', app.db.base.JSONColumn(), nullable=False),
    sa.Column('company_types', app.db.base.JSONColumn(), nullable=False),
    sa.Column('industries', app.db.base.JSONColumn(), nullable=False),
    sa.Column('preferred_companies', app.db.base.JSONColumn(), nullable=False),
    sa.Column('excluded_companies', app.db.base.JSONColumn(), nullable=False),
    sa.Column('must_have_keywords', app.db.base.JSONColumn(), nullable=False),
    sa.Column('nice_to_have_keywords', app.db.base.JSONColumn(), nullable=False),
    sa.Column('excluded_keywords', app.db.base.JSONColumn(), nullable=False),
    sa.Column('review_threshold', sa.Integer(), nullable=False),
    sa.Column('high_priority_threshold', sa.Integer(), nullable=False),
    sa.Column('scoring_weights', app.db.base.JSONColumn(), nullable=False),
    sa.Column('daily_application_cap', sa.Integer(), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('auto_submit_enabled', sa.Boolean(), nullable=False),
    sa.Column('discovery_schedule_cron', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('semantic_scoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('semantic_weight', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('job_sources',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('adapter_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('config', app.db.base.JSONColumn(), nullable=False),
    sa.Column('credential_ref', sa.String(length=32), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=False),
    sa.Column('query_templates', app.db.base.JSONColumn(), nullable=False),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('source_rules', app.db.base.JSONColumn(), nullable=False),
    sa.Column('health', sa.String(length=20), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_job_source_name')
    )
    with op.batch_alter_table('job_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_sources_user_id'), ['user_id'], unique=False)

    op.create_table('match_rules',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=30), nullable=False),
    sa.Column('value', app.db.base.JSONColumn(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_hard', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_rules_user_id'), ['user_id'], unique=False)

    op.create_table('notification_channels',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('channel_type', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', app.db.base.JSONColumn(), nullable=False),
    sa.Column('credential_ref', sa.String(length=32), nullable=True),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_type', name='uq_notification_channel')
    )
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_channels_user_id'), ['user_id'], unique=False)

    op.create_table('notification_events',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('channel_type', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('payload', app.db.base.JSONColumn(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_events_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_notification_events_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_events_user_id'), ['user_id'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('event_routing', app.db.base.JSONColumn(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=False),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('daily_digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_digest_time', sa.String(length=5), nullable=False),
    sa.Column('weekly_summary_enabled', sa.Boolean(), nullable=False),
    sa.Column('instant_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('failures_only', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('recruiters',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruiters_user_id'), ['user_id'], unique=False)

    op.create_table('resumes',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', app.db.base.JSONColumn(), nullable=False),
    sa.Column('role_focus', app.db.base.JSONColumn(), nullable=False),
    sa.Column('industry_focus', app.db.base.JSONColumn(), nullable=False),
    sa.Column('skill_focus', app.db.base.JSONColumn(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('current_version_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_user_id'), ['user_id'], unique=False)

    op.create_table('saved_searches',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('keywords', app.db.base.JSONColumn(), nullable=False),
    sa.Column('locations', app.db.base.JSONColumn(), nullable=False),
    sa.Column('remote_only', sa.Boolean(), nullable=False),
    sa.Column('min_salary_lpa', sa.Float(), nullable=True),
    sa.Column('employment_types', app.db.base.JSONColumn(), nullable=False),
    sa.Column('source_ids', app.db.base.JSONColumn(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=False),
    sa.Column('last_run_at', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_saved_search_name')
    )
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_searches_user_id'), ['user_id'], unique=False)

    op.create_table('schedules',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('cron', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('agent_key', sa.String(length=60), nullable=False),
    sa.Column('payload', app.db.base.JSONColumn(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_schedule_key')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_user_id'), ['user_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', app.db.base.JSONColumn(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_system_setting_key')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_user_id'), ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=True),
    sa.Column('agent_key', sa.String(length=60), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('items_succeeded', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('summary', app.db.base.JSONColumn(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index('ix_agent_runs_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_user_id'), ['user_id'], unique=False)

    op.create_table('career_facts',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('tags', app.db.base.JSONColumn(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('career_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_facts_profile_id'), ['profile_id'], unique=False)

    op.create_table('education',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=False),
    sa.Column('field_of_study', sa.String(length=200), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_education_profile_id'), ['profile_id'], unique=False)

    op.create_table('experiences',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('highlights', app.db.base.JSONColumn(), nullable=False),
    sa.Column('tech_stack', app.db.base.JSONColumn(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiences_profile_id'), ['profile_id'], unique=False)

    op.create_table('jobs',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('company_normalized', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('canonical_url', sa.String(length=1000), nullable=False),
    sa.Column('apply_url', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_hash', sa.String(length=64), nullable=False),
    sa.Column('salary_min_lpa', sa.Float(), nullable=True),
    sa.Column('salary_max_lpa', sa.Float(), nullable=True),
    sa.Column('salary_raw', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('experience_min_years', sa.Float(), nullable=True),
    sa.Column('experience_max_years', sa.Float(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('canonical_job_id', sa.String(length=32), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_sources', app.db.base.JSONColumn(), nullable=False),
    sa.Column('raw_payload', app.db.base.JSONColumn(), nullable=False),
    sa.Column('embedding', app.db.base.Vector(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['canonical_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_job_dedupe_key')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_canonical_job_id'), ['canonical_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_canonical_url'), ['canonical_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_company_normalized'), ['company_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_description_hash'), ['description_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_jobs_user_status', ['user_id', 'status'], unique=False)

    op.create_table('profile_skills',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('skill_id', sa.String(length=32), nullable=False),
    sa.Column('years', sa.Float(), nullable=True),
    sa.Column('proficiency', sa.String(length=40), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('evidence_note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'skill_id', name='uq_profile_skill')
    )
    with op.batch_alter_table('profile_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_skills_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_skills_skill_id'), ['skill_id'], unique=False)

    op.create_table('projects',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('tech_stack', app.db.base.JSONColumn(), nullable=False),
    sa.Column('highlights', app.db.base.JSONColumn(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_profile_id'), ['profile_id'], unique=False)

    op.create_table('resume_versions',
    sa.Column('resume_id', sa.String(length=32), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('origin', sa.String(length=40), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('sections', app.db.base.JSONColumn(), nullable=False),
    sa.Column('extracted_skills', app.db.base.JSONColumn(), nullable=False),
    sa.Column('parse_status', sa.String(length=30), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=False),
    sa.Column('tailored_for_job_id', sa.String(length=32), nullable=True),
    sa.Column('generation_notes', app.db.base.JSONColumn(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'version_number', name='uq_resume_version_number')
    )
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_versions_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_versions_resume_id'), ['resume_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_versions_tailored_for_job_id'), ['tailored_for_job_id'], unique=False)

    op.create_table('agent_run_steps',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', app.db.base.JSONColumn(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_run_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_run_steps_run_id'), ['run_id'], unique=False)

    op.create_table('answer_bank',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('normalized_key', sa.String(length=200), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('variables', app.db.base.JSONColumn(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('company_normalized', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer_bank', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_bank_company_normalized'), ['company_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_bank_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_answer_bank_user_key', ['user_id', 'normalized_key'], unique=False)

    op.create_table('applications',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('resume_version_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=60), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action', sa.String(length=200), nullable=False),
    sa.Column('next_action_due', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('outcome_reason', sa.Text(), nullable=False),
    sa.Column('recruiter_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)
        batch_op.create_index('ix_applications_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_applications_user_status', ['user_id', 'status'], unique=False)

    op.create_table('job_events',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', app.db.base.JSONColumn(), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_job_id'), ['job_id'], unique=False)

    op.create_table('job_matches',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('deterministic_score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('breakdown', app.db.base.JSONColumn(), nullable=False),
    sa.Column('hard_fail_reasons', app.db.base.JSONColumn(), nullable=False),
    sa.Column('matched_skills', app.db.base.JSONColumn(), nullable=False),
    sa.Column('missing_skills', app.db.base.JSONColumn(), nullable=False),
    sa.Column('positive_signals', app.db.base.JSONColumn(), nullable=False),
    sa.Column('rule_results', app.db.base.JSONColumn(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recommended_resume_id', sa.String(length=32), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_matches_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_job_matches_user_decision', ['user_id', 'decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_matches_user_id'), ['user_id'], unique=False)

    op.create_table('job_skills',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('skill_slug', sa.String(length=120), nullable=False),
    sa.Column('skill_name', sa.String(length=120), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'skill_slug', name='uq_job_skill')
    )
    with op.batch_alter_table('job_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_skills_job_id'), ['job_id'], unique=False)

    op.create_table('resume_chunks',
    sa.Column('resume_version_id', sa.String(length=32), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('embedding', app.db.base.Vector(), nullable=True),
    sa.Column('embedding_model', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_chunks_resume_version_id'), ['resume_version_id'], unique=False)

    op.create_table('resume_evidence',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('resume_version_id', sa.String(length=32), nullable=True),
    sa.Column('career_fact_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('supporting_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('embedding', app.db.base.Vector(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['career_fact_id'], ['career_facts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_evidence_career_fact_id'), ['career_fact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_evidence_resume_version_id'), ['resume_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_evidence_user_id'), ['user_id'], unique=False)

    op.create_table('application_answers',
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('resolved_from', sa.String(length=40), nullable=False),
    sa.Column('answer_bank_id', sa.String(length=32), nullable=True),
    sa.Column('evidence_ids', app.db.base.JSONColumn(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_answers_application_id'), ['application_id'], unique=False)

    op.create_table('application_assets',
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('asset_type', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('generated_by', sa.String(length=60), nullable=False),
    sa.Column('model_used', sa.String(length=80), nullable=False),
    sa.Column('evidence_ids', app.db.base.JSONColumn(), nullable=False),
    sa.Column('validation', app.db.base.JSONColumn(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_assets_application_id'), ['application_id'], unique=False)

    op.create_table('application_status_history',
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=False),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_status_history_application_id'), ['application_id'], unique=False)

    op.create_table('followups',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followups_application_id'), ['application_id'], unique=False)
        batch_op.create_index('ix_followups_due', ['user_id', 'due_date', 'completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_followups_user_id'), ['user_id'], unique=False)

    op.create_table('interviews',
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('round_name', sa.String(length=120), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('interviewers', app.db.base.JSONColumn(), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_application_id'), ['application_id'], unique=False)

    op.create_table('offers',
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('base_lpa', sa.Float(), nullable=True),
    sa.Column('total_lpa', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('details', app.db.base.JSONColumn(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_application_id'), ['application_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_application_id'))

    op.drop_table('offers')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_application_id'))

    op.drop_table('interviews')
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followups_user_id'))
        batch_op.drop_index('ix_followups_due')
        batch_op.drop_index(batch_op.f('ix_followups_application_id'))

    op.drop_table('followups')
    with op.batch_alter_table('application_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_status_history_application_id'))

    op.drop_table('application_status_history')
    with op.batch_alter_table('application_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_assets_application_id'))

    op.drop_table('application_assets')
    with op.batch_alter_table('application_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_answers_application_id'))

    op.drop_table('application_answers')
    with op.batch_alter_table('resume_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_evidence_user_id'))
        batch_op.drop_index(batch_op.f('ix_resume_evidence_resume_version_id'))
        batch_op.drop_index(batch_op.f('ix_resume_evidence_career_fact_id'))

    op.drop_table('resume_evidence')
    with op.batch_alter_table('resume_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_chunks_resume_version_id'))

    op.drop_table('resume_chunks')
    with op.batch_alter_table('job_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_skills_job_id'))

    op.drop_table('job_skills')
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_matches_user_id'))
        batch_op.drop_index('ix_job_matches_user_decision')
        batch_op.drop_index(batch_op.f('ix_job_matches_job_id'))

    op.drop_table('job_matches')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_job_id'))

    op.drop_table('job_events')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('ix_applications_user_status')
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
        batch_op.drop_index('ix_applications_user_created')
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))

    op.drop_table('applications')
    with op.batch_alter_table('answer_bank', schema=None) as batch_op:
        batch_op.drop_index('ix_answer_bank_user_key')
        batch_op.drop_index(batch_op.f('ix_answer_bank_user_id'))
        batch_op.drop_index(batch_op.f('ix_answer_bank_company_normalized'))

    op.drop_table('answer_bank')
    with op.batch_alter_table('agent_run_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_run_steps_run_id'))

    op.drop_table('agent_run_steps')
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_versions_tailored_for_job_id'))
        batch_op.drop_index(batch_op.f('ix_resume_versions_resume_id'))
        batch_op.drop_index(batch_op.f('ix_resume_versions_checksum_sha256'))

    op.drop_table('resume_versions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_profile_id'))

    op.drop_table('projects')
    with op.batch_alter_table('profile_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_skills_skill_id'))
        batch_op.drop_index(batch_op.f('ix_profile_skills_profile_id'))

    op.drop_table('profile_skills')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_user_status')
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index('ix_jobs_user_created')
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_source_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_external_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_description_hash'))
        batch_op.drop_index(batch_op.f('ix_jobs_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_jobs_company_normalized'))
        batch_op.drop_index(batch_op.f('ix_jobs_company'))
        batch_op.drop_index(batch_op.f('ix_jobs_canonical_url'))
        batch_op.drop_index(batch_op.f('ix_jobs_canonical_job_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiences_profile_id'))

    op.drop_table('experiences')
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_education_profile_id'))

    op.drop_table('education')
    with op.batch_alter_table('career_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_facts_profile_id'))

    op.drop_table('career_facts')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_user_id'))
        batch_op.drop_index('ix_agent_runs_user_created')
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_key'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_refresh_token_hash'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_user_id'))

    op.drop_table('system_settings')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_user_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_searches_user_id'))

    op.drop_table('saved_searches')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_user_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruiters_user_id'))

    op.drop_table('recruiters')
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_user_id'))

    op.drop_table('notification_preferences')
    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_events_user_id'))
        batch_op.drop_index('ix_notification_events_user_created')
        batch_op.drop_index(batch_op.f('ix_notification_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_notification_events_dedupe_key'))

    op.drop_table('notification_events')
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_channels_user_id'))

    op.drop_table('notification_channels')
    with op.batch_alter_table('match_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_rules_user_id'))

    op.drop_table('match_rules')
    with op.batch_alter_table('job_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_sources_user_id'))

    op.drop_table('job_sources')
    with op.batch_alter_table('job_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_preferences_user_id'))

    op.drop_table('job_preferences')
    with op.batch_alter_table('encrypted_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encrypted_secrets_user_id'))

    op.drop_table('encrypted_secrets')
    with op.batch_alter_table('career_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_profiles_user_id'))

    op.drop_table('career_profiles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index('ix_audit_logs_user_created')
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_user_id'))
        batch_op.drop_index('ix_ai_usage_user_created')
        batch_op.drop_index(batch_op.f('ix_ai_usage_request_hash'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_function'))

    op.drop_table('ai_usage')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_user_id'))

    op.drop_table('agents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_slug'))

    op.drop_table('skills')
    with op.batch_alter_table('ai_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_cache_request_hash'))

    op.drop_table('ai_cache')
    # ### end Alembic commands ###
