"""add job application_email

Revision ID: 77caf9f20440
Revises: 60225360476a
Create Date: 2026-09-16 08:46:17.461562
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '77caf9f20440'
down_revision = '60225360476a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        # server_default lets this apply to a table that already has rows; the
        # column is NOT NULL, so existing jobs need a value.
        batch_op.add_column(
            sa.Column(
                'application_email',
                sa.String(length=320),
                nullable=False,
                server_default='',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('application_email')

    # ### end Alembic commands ###
